# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory

# @package _global_
root_dir: ${oc.env:PROJECT_ROOT}
exp_dir: /data/scratch/acw572


# path to data directory
data_dir: /data/EECS-MachineListeningLab/datasets/AudioSet
meta_dir: /data/EECS-MachineListeningLab/shubhr/hgann
# path to logging directory
log_dir: ${paths.exp_dir}/LHGNN/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
