defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - tqdm_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mAP"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 20

early_stopping:
  monitor: "val/loss"
  patience: 5
  mode: "min"

model_summary:
  max_depth: -1


  
  
