# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html

early_stopping:
  _target_: pytorch_lightning.callbacks.StochasticWeightAveraging
  swa_lrs: 1e-2 # quantity to be monitored, must be specified !!!
  swa_epoch_start: 0.5, 
  annealing_epochs: 15, 
  annealing_strategy: 'linear'
  avg_fn: None # whether to run early stopping at the end of the training epoch
  # log_rank_zero_only: False  # this keyword argument isn't available in stable version
